export * from './Logo'
export * from './ExelIcon'
export * from './MailIcon'
export * from './PhoneIcon'
export * from './Capitronbank'
export * from './QpayIcon'
export * from './PlateTemplate'
export * from './EbarimtIcon'