export * from './header-footer'
export * from './home'
export * from './product-detail'
export * from './global'
export * from './cart'
export * from './cards'
export * from './payment'
export * from './product-list'